apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-lan-sc01
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lan-vm-pv01
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-lan-sc01
  local:
    path: /var/lib/kubevirt-disks/lan-vm01
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lan-vm-pvc01
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-lan-sc01
  resources:
    requests:
      storage: 20Gi
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: lan-bridge-net01
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "br-lan",
      "promiscMode": true
    }
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-lan-vm02
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-lan-vm02
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: osdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
            - name: datadisk
              disk:
                bus: virtio
          interfaces:
            - name: podnet
              masquerade: {}
            - name: lannet
              bridge: {}
      networks:
        - name: podnet
          pod: {}
        - name: lannet
          multus:
            networkName: lan-bridge-net01
      volumes:
        - name: osdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #cloud-config
              ssh_pwauth: true
              disable_root: false
              chpasswd:
                list: |
                  root:root123
                expire: false

              network:
                version: 2
                ethernets:
                  enp2s0:
                    dhcp4: true
                    dhcp6: false
                    accept-ra: false

              runcmd:
                - ip link set enp2s0 up
                - dhclient enp2s0
                - netplan apply
                - sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
                - sed -i 's/^PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
                - systemctl restart ssh
                - apt-get update
                - apt-get install -y qemu-guest-agent
                - systemctl enable --now qemu-guest-agent
        - name: datadisk
          persistentVolumeClaim:
            claimName: lan-vm-pvc01
